services:
  web-test:
    container_name: coin-control-web-test
    tty: true
    profiles:
      - once
    build:
      target: test
      dockerfile: ./web/web.Dockerfile
    environment:
      - VITE_PORT=${WEB_PORT}
      - VITE_API_URL=http://localhost:3001
    command: pnpm --filter web test

  web-test-coverage:
    container_name: coin-control-web-test-coverage
    tty: true
    profiles:
      - coverage
    build:
      target: test
      dockerfile: ./web/web.Dockerfile
    environment:
      - VITE_PORT=3000
      - VITE_API_URL=http://localhost:3001
    command: pnpm --filter web test:coverage

  web-test-watch:
    container_name: coin-control-web-test-watch
    tty: true
    profiles:
      - watch
    volumes:
      - ./web/src:/app/web/src
    build:
      target: test
      dockerfile: ./web/web.Dockerfile
    environment:
      - VITE_PORT=3000
      - VITE_API_URL=http://localhost:3001
    command: pnpm --filter web test:watch

  web-test-watch-coverage:
    container_name: coin-control-web-test-watch-coverage
    tty: true
    profiles:
      - watch-coverage
    volumes:
      - ./web/src:/app/web/src
    build:
      target: test
      dockerfile: ./web/web.Dockerfile
    environment:
      - VITE_PORT=3000
      - VITE_API_URL=http://localhost:3001
    command: pnpm --filter web test:watch-coverage
