services:
  avatar-service:
    image: nginx:1-alpine
    container_name: coin-control-avatars
    ports:
      - 8089:80
    volumes:
      - ./api/avatar-upload/:/coin-control-avatars
      - ./avatar-service/nginx.conf:/etc/nginx/conf.d/default.conf
      - avatar-cache:/var/cache/nginx/static

  database:
    image: postgres:17.4-alpine
    container_name: coin-control-database
    restart: always
    environment:
      PGUSER: postgres
      PGDATABASE: coin_control
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coin_control
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - app-network
    volumes:
      - coin-control-database-data:/var/lib/postgresql/data
  cache:
    image: redis:6.2-alpine
    container_name: coin-control-cache
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-a",
          "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81",
          "--raw",
          "incr",
          "ping",
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - app-network
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

  worker:
    image: ghcr.io/maciejgarncarski/coin-control-worker:latest
    container_name: coin-control-worker-prod
    pull_policy: always
    build:
      target: prod
      dockerfile: ./worker/worker.Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - cache
      - database
    networks:
      - app-network
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - APP_ORIGIN=${APP_URL}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

  api:
    image: ghcr.io/maciejgarncarski/coin-control-api:latest
    pull_policy: always
    container_name: coin-control-api-prod
    depends_on:
      - cache
      - worker
      - database
    networks:
      - app-network
    build:
      target: prod
      dockerfile: ./api/api.Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./api/avatar-upload:/prod/api/avatar-upload
    environment:
      - PORT=${API_PORT}
      - APP_ORIGIN=${APP_URL}
      - API_URL=${API_URL}
      - HOST=${HOST}
      - DATABASE_URL=${DATABASE_URL}
      - API_SECRET=${API_SECRET}
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_OAUTH_URL=${GOOGLE_OAUTH_URL}
      - GOOGLE_ACCESS_TOKEN_URL=${GOOGLE_ACCESS_TOKEN_URL}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}

  web:
    image: ghcr.io/maciejgarncarski/coin-control-web:latest
    pull_policy: always
    container_name: coin-control-web-prod
    build:
      dockerfile: ./web/web.Dockerfile
      args:
        VITE_API_URL: ${API_URL}
        NODE_ENV: production
    depends_on:
      - api
    environment:
      - NODE_ENV=production
    ports:
      - "${WEB_PORT}:80"

networks:
  app-network:
    driver: bridge

volumes:
  avatar-cache:
    driver: local

  cache:
    driver: local

  coin-control-database-data:
    driver: local
