packages:
  - shared/*
  - worker
  - api
  - web

catalog:
  "@types/node": 25.2.2
  typescript: 5.9.3
  eslint: 9.39.2
  prettier: 3.8.1
  tsdown: 0.20.3
  tsx: 4.21.0
  nodemailer: 8.0.1
  "@types/nodemailer": 7.0.9
  vite: 7.3.1
  vitest: 4.0.18
  "@vitest/coverage-istanbul": 4.0.18
  "@vitest/coverage-v8": 4.0.18

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - prisma
ignoredBuiltDependencies:
  - esbuild
  - msgpackr-extract
