packages:
  - shared/*
  - worker
  - api
  - web

catalog:
  "@types/node": 25.2.2
  typescript: 5.9.3
  eslint: 9.39.2
  prettier: 3.8.1

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - prisma
ignoredBuiltDependencies:
  - esbuild
  - msgpackr-extract
