packages:
  - shared/*
  - worker
  - api
  - web

catalogs:
  prisma:
    prisma: latest

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - prisma
ignoredBuiltDependencies:
  - esbuild
  - msgpackr-extract
