// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users.js'

/** Identifier type for public.otp_codes */
export type OtpCodesId = string & { __brand: 'OtpCodesId' }

/** Represents the table public.otp_codes */
export default interface OtpCodes {
  id: OtpCodesId

  user_id: UsersId

  otp: string

  expires_at: Date

  used: boolean | null

  created_at: Date | null
}

/** Represents the initializer for the table public.otp_codes */
export interface OtpCodesInitializer {
  id: OtpCodesId

  user_id: UsersId

  otp: string

  expires_at: Date

  /** Default value: false */
  used?: boolean | null

  /** Default value: now() */
  created_at?: Date | null
}

/** Represents the mutator for the table public.otp_codes */
export interface OtpCodesMutator {
  id?: OtpCodesId

  user_id?: UsersId

  otp?: string

  expires_at?: Date

  used?: boolean | null

  created_at?: Date | null
}
