// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.sessions */
export type SessionsSid = string & { __brand: 'SessionsSid' }

/** Represents the table public.sessions */
export default interface Sessions {
  sid: SessionsSid

  data: string

  expire_at: Date
}

/** Represents the initializer for the table public.sessions */
export interface SessionsInitializer {
  sid: SessionsSid

  data: string

  expire_at: Date
}

/** Represents the mutator for the table public.sessions */
export interface SessionsMutator {
  sid?: SessionsSid

  data?: string

  expire_at?: Date
}
