// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.users */
export type UsersId = string & { __brand: 'UsersId' }

/** Represents the table public.users */
export default interface Users {
  id: UsersId

  email: string

  password_hash: string

  created_at: Date | null

  name: string | null

  email_verified: boolean | null
}

/** Represents the initializer for the table public.users */
export interface UsersInitializer {
  id: UsersId

  email: string

  password_hash: string

  /** Default value: now() */
  created_at?: Date | null

  name?: string | null

  /** Default value: false */
  email_verified?: boolean | null
}

/** Represents the mutator for the table public.users */
export interface UsersMutator {
  id?: UsersId

  email?: string

  password_hash?: string

  created_at?: Date | null

  name?: string | null

  email_verified?: boolean | null
}
