name: Publish Docker Images

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          docker buildx build \
            --push \
            --target prod \
            --tag ghcr.io/maciejgarncarski/coin-control-api:latest \
            --tag ghcr.io/maciejgarncarski/coin-control-api:${{ github.sha }} \
            -f docker/api.Dockerfile .

          docker buildx build \
            --push \
            --target prod \
            --tag ghcr.io/maciejgarncarski/coin-control-worker:latest \
            --tag ghcr.io/maciejgarncarski/coin-control-worker:${{ github.sha }} \
            -f docker/worker.Dockerfile .
