name: tests-web

on:
  push:
    branches:
      - main

jobs:
  tests-web:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:28.0.4
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest

      - name: Build the frontend image with cache
        uses: docker/build-push-action@v6
        with:
          load: true
          context: .
          file: api/api.Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run tests
        run: docker compose -f docker-compose.test-web.yml --profile once up --abort-on-container-exit

      - name: Compose down
        if: always()
        run: docker compose -f docker-compose.test-web.yml down
