name: tests-api

on:
  push:
    branches:
      - main

jobs:
  tests-api:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:28.0.4
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Build the frontend image
        uses: docker/build-push-action@v6
        with:
          load: true
          context: .
          file: api/api.Dockerfile

      - name: Run tests
        run: docker compose -f docker-compose.test-api.yml --profile once up --abort-on-container-exit

      - name: Compose down
        if: always()
        run: docker compose -f docker-compose.test-api.yml down
