name: tests-web

on:
  push:
    branches:
      - main

jobs:
  tests-web:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:28.0.4
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v3

      - name: Build the frontend image
        uses: docker/build-push-action@v4
        with:
          load: true
          context: .
          file: web/web.Dockerfile

      - name: Run tests
        run: docker compose -f docker-compose.test-web.yml --profile once up --abort-on-container-exit

      - name: Compose down
        if: always()
        run: docker compose -f docker-compose.test-web.yml down
